#
# TransFig makefile
#

all: archi.pdf fullarchi.pdf genc.pdf generationStep.pdf newarchi.pdf projection.pdf proj.pdf theoremca.pdf theorem_Coq2C.pdf theorem.pdf 

# translation into pdf

archi.pdf: archi.fig Makefile
	fig2dev -L pdf archi.fig archi.pdf
clean::
	rm -f archi.pdf


# translation into pdf

fullarchi.pdf: fullarchi.fig Makefile
	fig2dev -L pdf fullarchi.fig fullarchi.pdf
clean::
	rm -f fullarchi.pdf


# translation into pdf

genc.pdf: genc.fig Makefile
	fig2dev -L pdf genc.fig genc.pdf
clean::
	rm -f genc.pdf


# translation into pdf

generationStep.pdf: generationStep.fig Makefile
	fig2dev -L pdf generationStep.fig generationStep.pdf
clean::
	rm -f generationStep.pdf


# translation into pdf

newarchi.pdf: newarchi.fig Makefile
	fig2dev -L pdf newarchi.fig newarchi.pdf
clean::
	rm -f newarchi.pdf


# translation into pdf

projection.pdf: projection.fig Makefile
	fig2dev -L pdf projection.fig projection.pdf
clean::
	rm -f projection.pdf


# translation into pdf

proj.pdf: proj.fig Makefile
	fig2dev -L pdf proj.fig proj.pdf
clean::
	rm -f proj.pdf


# translation into pdf

theoremca.pdf: theoremca.fig Makefile
	fig2dev -L pdf theoremca.fig theoremca.pdf
clean::
	rm -f theoremca.pdf


# translation into pdf

theorem_Coq2C.pdf: theorem_Coq2C.fig Makefile
	fig2dev -L pdf theorem_Coq2C.fig theorem_Coq2C.pdf
clean::
	rm -f theorem_Coq2C.pdf


# translation into pdf

theorem.pdf: theorem.fig Makefile
	fig2dev -L pdf theorem.fig theorem.pdf
clean::
	rm -f theorem.pdf

